data:
  extra_train_datasets:
    - dataset_type: laion_synthetic
      data_root: /home/devdata/laion/edge_detection
      image_root: /home/devdata/laion/edge_detection/edge_detection
      bezier_root: /home/devdata/laion/edge_detection/laion_edge_v3_bezier
      batch_glob: batch*
      entry_cache_path: /home/devdata/laion/edge_detection/laion_entry_cache_v3_bezier.txt
      selection_seed: 20260318
      selection_offset: 2048
  val_dataset:
    dataset_type: laion_synthetic
    data_root: /home/devdata/laion/edge_detection
    image_root: /home/devdata/laion/edge_detection/edge_detection
    bezier_root: /home/devdata/laion/edge_detection/laion_edge_v3_bezier
    batch_glob: batch*
    entry_cache_path: /home/devdata/laion/edge_detection/laion_entry_cache_v3_bezier.txt
    selection_seed: 20260318
    selection_offset: 0
    max_samples: 1024
  test_dataset:
    dataset_type: laion_synthetic
    data_root: /home/devdata/laion/edge_detection
    image_root: /home/devdata/laion/edge_detection/edge_detection
    bezier_root: /home/devdata/laion/edge_detection/laion_edge_v3_bezier
    batch_glob: batch*
    entry_cache_path: /home/devdata/laion/edge_detection/laion_entry_cache_v3_bezier.txt
    selection_seed: 20260318
    selection_offset: 1024
    max_samples: 1024

trainer:
  default_root_dir: /home/viplab/jiaxin/parametric_edge_prediction/outputs/parametric_edge_training/laion-dab-v3-lab30-2gpu-dn-aux-ce
  devices: 2
  strategy: ddp_find_unused_parameters_true
  use_distributed_sampler: true
  precision: 32-true
  accumulate_grad_batches: auto
  effective_batch_size: 64

logging:
  csv: true
  wandb:
    enabled: true
