trainer:
  default_root_dir: outputs/parametric_edge_training/overfit_diverse16_2000_addback_onetomany

loss:
  one_to_many_weight: 0.3

logging:
  wandb:
    name: overfit-diverse16-2000-addback-onetomany
    tags:
      - overfit
      - gpu
      - diverse16
      - 2000epoch
      - addback
      - one-to-many
    save_dir: outputs/parametric_edge_training/overfit_diverse16_2000_addback_onetomany/wandb
