trainer:
  default_root_dir: outputs/parametric_edge_training/overfit_diverse16_2000_addback_topk

loss:
  topk_positive_weight: 0.2

logging:
  wandb:
    name: overfit-diverse16-2000-addback-topk
    tags:
      - overfit
      - gpu
      - diverse16
      - 2000epoch
      - addback
      - topk
    save_dir: outputs/parametric_edge_training/overfit_diverse16_2000_addback_topk/wandb
