trainer:
  default_root_dir: outputs/parametric_edge_training/overfit_diverse16_2000_addback_aux

loss:
  aux_weight: 0.5

logging:
  wandb:
    name: overfit-diverse16-2000-addback-aux
    tags:
      - overfit
      - gpu
      - diverse16
      - 2000epoch
      - addback
      - aux
    save_dir: outputs/parametric_edge_training/overfit_diverse16_2000_addback_aux/wandb
