trainer:
  default_root_dir: outputs/parametric_edge_training/overfit_diverse16_2000_all_except_dn

loss:
  aux_weight: 0.5
  dn_weight: 0.0
  dn_curve_weight: 0.0
  one_to_many_weight: 0.3
  topk_positive_enabled: true
  topk_positive_layer_k: [2, 2, 2, 2, 2]
  topk_positive_weight: 0.2
  distinct_weight: 0.1

model:
  dn_num_groups: 0
  dn_noise_scale: 0.0

logging:
  wandb:
    name: overfit-diverse16-2000-all-except-dn
    tags:
      - overfit
      - gpu
      - diverse16
      - 2000epoch
      - ablation
      - all-except-dn
    save_dir: outputs/parametric_edge_training/overfit_diverse16_2000_all_except_dn/wandb