data:
  train_augment: false
  batch_size: 1
  val_batch_size: 1
  num_workers: 0
  persistent_workers: false
  pin_memory: false
  extra_train_datasets:
    - dataset_type: laion_synthetic
      data_root: /data/jiaxin/laion/edge_detection
      image_root: /data/jiaxin/laion/edge_detection
      bezier_root: /data/jiaxin/laion/edge_detection/laion_edge_v3_bezier
      batch_glob: batch*
      entry_cache_path: /data/jiaxin/laion/edge_detection/laion_entry_cache_v3_bezier.txt
      selection_seed: 20260318
      selection_offset: 0
      max_samples: 1
  val_dataset:
    dataset_type: laion_synthetic
    data_root: /data/jiaxin/laion/edge_detection
    image_root: /data/jiaxin/laion/edge_detection
    bezier_root: /data/jiaxin/laion/edge_detection/laion_edge_v3_bezier
    batch_glob: batch*
    entry_cache_path: /data/jiaxin/laion/edge_detection/laion_entry_cache_v3_bezier.txt
    selection_seed: 20260318
    selection_offset: 0
    max_samples: 1
  test_dataset:
    dataset_type: laion_synthetic
    data_root: /data/jiaxin/laion/edge_detection
    image_root: /data/jiaxin/laion/edge_detection
    bezier_root: /data/jiaxin/laion/edge_detection/laion_edge_v3_bezier
    batch_glob: batch*
    entry_cache_path: /data/jiaxin/laion/edge_detection/laion_entry_cache_v3_bezier.txt
    selection_seed: 20260318
    selection_offset: 0
    max_samples: 1

model:
  arch: dab_cond_curve_detr
  curve_query_init_type: random
  conditioned_curve_init_enabled: true
  conditioned_curve_init_checkpoint: /data/jiaxin/parametric_edge_prediction/experiments/init_checkpoints/curve_dab_v3_cluster_line_last.ckpt


trainer:
  default_root_dir: /data/jiaxin/parametric_edge_prediction/outputs/conditioned-curve-overfit1-lab34
  devices: 1
  strategy: auto
  precision: 32-true
  effective_batch_size: 1
  accumulate_grad_batches: 1
  max_epochs: 30
  overfit_batches: 1
  limit_train_batches: 1
  limit_val_batches: 1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  run_test_after_fit: false

callbacks:
  visualization_every_n_epochs: 1
  visualization_every_n_train_steps: 1
  visualization_score_threshold: 0.3
  visualization_max_curves: 300

loss:
  curve_distance_type: ordered

logging:
  csv: true
  wandb:
    enabled: false
